baseURL = "https://hjwu.github.io/"
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[markup]
[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = false
style = "pastie"
tabWidth = 4

[params]
title = "陳馬尼 我想你"
signature = "I Love You 8128"
# cover = "https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg"

# name = "Moments 主题"
# avatar = "moment-avatar.png"

infiniteScroll = false

[params.features]
pangu = true

[params.experimental]
comment = false
